### ISSUE TITLE
Netbeans 8.1 / 8.2

### ISSUE THREAD

**Issue by Indigo744** [garethflowers/netbeans-portable#1]
Hello,
Thanks for this portable tool!
What about Netbeans 8.1 / 8.2 ? 

Thanks

**Comment by garethflowers** [comment]
It's on the todo list...

**Comment by Indigo744** [comment]
Nice! Watching this repo and waiting for next version :) 
Thanks a lot!

**Comment by Indigo744** [comment]
Just saw the recent release. Thank you! Downloading right now :)

For updating, can I just extract the ZIP file on top of the other version ? In order to keep my configuration and such.

**Comment by garethflowers** [comment]
Yes, just extract over the top. Any user specific data (i.e. configuration files) are saved in the `./Data` directory so will be unaffected.

**Comment by Indigo744** [comment]
I actually used the "Export configuration" option, and imported it in the new version. Worked pretty well. Next time, I may just overwrite everything as you said. Anyway, works great, thanks a lot!
